# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
