# Generated by Django 2.0 on 2017-12-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20171212_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(help_text='売り上げ金額を記入してください', null=True),
        ),
    ]
