# Generated by Django 2.0 on 2017-12-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20171212_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=100, help_text='売り上げ金額を記入してください'),
            preserve_default=False,
        ),
    ]
