# Generated by Django 2.0 on 2017-12-12 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20171212_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='販売日時を入力してください'),
            preserve_default=False,
        ),
    ]
