# Generated by Django 2.0 on 2017-12-21 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20171218_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='label',
            new_name='name',
        ),
    ]
