# Generated by Django 2.0 on 2017-12-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20171218_2354'),
        ('sales', '0008_auto_20171221_1228'),
    ]

    operations = [
    ]
